- id: tfcoach
  name: tfcoach
  entry: tfcoach
  args:
    - lint
  language: golang
  types:
    - terraform
- id: tfcoach-docker
  name: tfcoach-docker
  entry: ghcr.io/marcel2603/tfcoach/tfcoach
  args:
    - lint
  language: docker_image
  types:
    - terraform
