preset: angular
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/github"
  -  - "@semantic-release/exec"
     -  failCmd: "bash .github/scripts/rollback_release.sh ${nextRelease.version} ${env.GITHUB_REPOSITORY} ${env.GITHUB_TOKEN}"
        publishCmd: |
          echo "${nextRelease.notes}" > /tmp/release-notes.md
          goreleaser release --release-notes /tmp/release-notes.md --clean      
branches:
  - main
