//go:build tfcoach_tools

package main

import (
	"bytes"
	"log"
	"os"
	"sort"
	"strings"

	"github.com/Marcel2603/tfcoach/cmd"
	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

func collectCommands(cmd *cobra.Command) []*cobra.Command {
	cmds := []*cobra.Command{cmd}
	for _, c := range cmd.Commands() {
		cmds = append(cmds, collectCommands(c)...)
	}
	return cmds
}

func GenerateUsage(filename string) {
	var buf bytes.Buffer
	buf.WriteString("# Usage \n")

	cmds := collectCommands(cmd.GetRootCommand())
	sort.Slice(cmds, func(i, j int) bool { return cmds[i].CommandPath() < cmds[j].CommandPath() })

	for _, command := range cmds {
		var section bytes.Buffer

		err := doc.GenMarkdownCustom(
			command,
			&section,
			func(_ string) string {
				// Mark links to be deleted
				return "delete_me"
			},
		)
		if err != nil {
			log.Fatalf("error generating markdown for %s: %v", command.Name(), err)
		}

		out := cleanMarkdown(section.String())
		buf.WriteString(out)
		buf.WriteString("\n")
	}

	if err := os.WriteFile(filename, buf.Bytes(), 0644); err != nil {
		log.Fatal(err)
	}
}

func cleanMarkdown(s string) string {
	lines := strings.Split(s, "\n")
	var cleaned []string

	for _, line := range lines {
		if strings.HasPrefix(line, "### SEE ALSO") ||
			strings.Contains(line, "Auto generated by spf13/cobra") ||
			strings.Contains(line, "delete_me") {
			continue
		}
		cleaned = append(cleaned, line)
	}

	s = strings.Join(cleaned, "\n")

	return strings.TrimSpace(s) + "\n"
}
