name: Release

on:
  push:
    branches: [ main ]
  workflow_run:
    branches: [main]
    workflows:
      - "Test & Lint"
    types:
      - completed

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write   # needed for GHCR
  id-token: write

jobs:
  semantic_release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Semantic Release
    runs-on: ubuntu-latest

    outputs:
      published: ${{ steps.sr.outputs.new_release_published }}
      tag: ${{ steps.sr.outputs.new_release_git_tag }}
      version: ${{ steps.sr.outputs.new_release_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: true
          cache-dependency-path: |
            go.sum

      - name: Go Mod Download
        run: go mod download

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true
          version: "~> v2"

      - name: Set up QEMU (for multi-arch Docker builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Semantic Release
        id: sr
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          extra_plugins: |
            "@semantic-release/exec"
