name: Release-gate

on:
  workflow_dispatch: {}  # optional manual trigger

permissions:
  contents: read
  packages: write   # needed for GHCR

jobs:
  release:
    environment: release
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/release
        env:
          APP_ID: ${{ secrets.RELEASE_APP_ID }}
          PRIVATE_KEY: ${{ secrets.RELEASE_APP_PRIVATE_KEY_BASE64 }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
